# -----------------------------------------------
# File: config.yml
# Lokasi: root proyek (di samping go.mod)
# -----------------------------------------------
server:
  port: "8080" # Port untuk API Ingress Golang

redis:
  addr: "redis:6379" # 'redis' adalah nama service di docker-compose
  streamname: "nexus_stream"
  consumergroup: "nexus_group"

database:
  # DSN (Data Source Name) untuk koneksi ke DB Utama Nexus
  # Format: user:password@tcp(host:port)/dbname
  # 'db' adalah nama service di docker-compose
  nexus_db_dsn: "demo_user:demo_password@tcp(db:3306)/nexus_db"

# Peta koneksi ke Database Tujuan
# Nama di sini (misal: "mysql_support") HARUS SAMA PERSIS
# dengan yang Anda masukkan di Filament (`target_connection_name`)
targets:
  mysql_support: "demo_user:demo_password@tcp(db:3306)/db_support"
  mysql_billing: "demo_user:demo_password@tcp(db:3306)/db_billing"
  mysql_audit: "demo_user:demo_password@tcp(db:3306)/db_audit_log"
